### PR TITLE
new global.json sdk version

### PR DESCRIPTION
**Pull request by damienbod**

### CODE REVIEW

**Comment by damienbod** [comment]
@brockallen @leastprivilege 
fix for this issue
https://github.com/IdentityServer/IdentityServer4.Samples/issues/91

**Comment by brockallen** [comment]
Oh we just crossed paths -- I just pushed these changes. Thanks though!

**Comment by damienbod** [comment]
Hi @brockallen you used an old version!

**Comment by damienbod** [comment]
Should be 1.0.0-preview2-1-003177

**Comment by brockallen** [comment]
What version do you get when you do a File => New ASP.NET Core app?

**Comment by damienbod** [comment]
From what I understand 1.0.0-preview2-003131is the patch release in the ASP.NET Core September 2016 Patch Release

1.0.0-preview2-1-003177 is the 1.1.0 release. I don't know if it makes a difference.

Greetings Damien

**Comment by brockallen** [comment]
They don't say to update it in this article: https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/

Also, from what I understand xunit has problems with the newer SDK.

**Comment by damienbod** [comment]
ok

**Pull request closed without merging**
