### PR TITLE
Removes all the client ids adds constant.

### PR DESCRIPTION
**Pull request by LindaLawton**
I have removed the hard coded client ids from the project its against Googles [TOS](https://developers.googleblog.com/2014/11/subject-changes-to-google-apis-terms-of.html) to share your client id with anyone.   Placing it in a OS project its a bad idea. 

> Asking developers to make reasonable efforts to keep their private keys private and not embed them in open source projects.

Who ever created these keys should remove them in Google developer console to prevent anyone from miss using them and you loosing access to your account.    

## Question:  
Should i add some instructions in the README's on these projects as to how to create the clients or is it good enough pointing them to the tutorial?

### CODE REVIEW

**Comment by LindaLawton** [comment]
any feedback on this?

**Comment by brockallen** [comment]
We've both been busy/traveling. We might have time this week to catch up on IdentityServer issues...

**Comment by LindaLawton** [comment]
two months on this should I just close it as rejected?

**Comment by LindaLawton** [comment]
Are we going for the longest lived pull request on an active project record?    I will check back in a few months.

**Comment by leastprivilege** [comment]
We agree that it's not best practices to put client ID / secrets into source code.

But the client is for localhost only, and only authorized to use the Google+ API (login only). Given the complexity of getting up and running with these technologies - I think it is quite nice that Google logins work out of the box without having to explain those details as well.

If you want to contribute a new page to our docs that explains the registration process in Google and the necessary configuration, we could remove the hard-coded values. Are you up for that?

**Comment by LindaLawton** [comment]
yes definitely becouse what you are doing is against Google TOS which you aggreed to when you created your account.  I have several on my own website the only issue is that Google changes the layout a few times a year I gave up updating the pictures two years ago.

rember this also is leaving your personal Gmail account open to attach as well as anyone can see it as well as the  client id and secret which you have not locked to a domain.  it can also be spamed if it's spammed enough Google will shut down your account and there is no way of getting it back that I have ever seen.

I am not only trying to help your users but as a Google developers expect its my job to help open source project like yours also follow the best practices set up by Google.

if you are interested I have several links on TOS you can read through.    Although I think I already linked most in the original pr.

**Comment by leastprivilege** [comment]
I removed the ids and secrets and added brief instructions 

https://github.com/IdentityServer/IdentityServer4.Samples/commit/82418a28fa7b1c3861f6599e2aa8d4dec51a7b46

Once we have a more detailed walkthrough in our docs, we can replace my text with a URL to that page. 

Let me know if you want to contribute such a page to our docs, then I can pre-create it and you PR the content.

thanks!

**Comment by LindaLawton** [comment]
I am happy to do it when I return from vacation.

**Pull request closed without merging**
