### PR TITLE
Update docker samples

### PR DESCRIPTION
**Pull request by tugberkugurlu**
> <strike>⚠️ Don't merge yet, it's not entirely working 😄 </strike>

This PR is to update the docker sample to latest Identity Server and .NET Core 1.1.0.

### CODE REVIEW

**Comment by tugberkugurlu** [comment]
Working now 🎉 

image

**Comment by tugberkugurlu** [comment]
It's ready for review.

**Comment by leastprivilege** [comment]
I am not in the position to review that, but if @alexzeitler gives a thumbs up - it's good enough for me ;)

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
