### PR TITLE
Make It Easy to Run "MVC and API" Sample Through Docker

### PR DESCRIPTION
**Pull request by tugberkugurlu**
With this, the sample can be run just by executing `docker-compose up` under the "MVC and API" directory + it doesn't require you to have .NET Core installed on your machine. I tested it on Mac but it should work on Linux and Windows.

I also added a README for that sample which should make it easy to understand how to run the sample.

### CODE REVIEW

**Comment by leastprivilege** [comment]
cool. thanks!

We actually wanted to delete this sample - but now it has become useful again ;)

**Comment by JGrzybowski** [comment]
So this will be the only sample how to host IDServ together with an application?

**Comment by brockallen** [comment]
@JGrzybowski no -- the reason for wanting to remove them was that they are redundant given the quickstarts.

**Comment by brockallen** [comment]
@tugberkugurlu @leastprivilege i'll rename to "docker" something. we can also make @tugberkugurlu  the docker PM.

**Comment by tugberkugurlu** [comment]
@leastprivilege @brockallen oh well, funny that I have just realised Quickstart samples 😄 

Do you think it's valuable to have this type of running experience for each of those, too?

**Comment by brockallen** [comment]
Well, I don't know docker so the fewer things that we have to support that I don't know the better.

**Comment by tugberkugurlu** [comment]
Cool, that's fair. It makes to run the samples to see what the product is like w/o caring about the dependencies, which projects to start, etc. but yeah, it will become the one more thing to babysit.

**Pull request merged**
