### PR TITLE
Android RO_Client for IdentityServer4

### PR DESCRIPTION
**Pull request by leo9223**
Android Resource Owner Flow Client for IdentityServer4

### CODE REVIEW

**Comment by leastprivilege** [comment]
Hi Leo, 

thank you very much!

I would prefer that you keep that sample in your repo - I will add a link to it to our documentation.

I know nothing about Android - but if it is part of our repo, people expect us to be able to answer questions and maintain it.

**Comment by leastprivilege** [comment]
Which link should I use?

**Comment by leo9223** [comment]
You very welcome so nice of you Sir :)
For sure I have to use it and we will make it better over the time. I am also beginner at android.

Sir can you please tell me about which link you are asking? My repo link? Or android doc link?

**Comment by leastprivilege** [comment]
repo link. Do you also have a readme?

**Comment by leo9223** [comment]
Thank you so much Sir its really honor for me to have my repo link in your docs :)

here is the link you can use https://github.com/leo9223/IdentityServer4.Samples

yes I have readme

**Comment by leo9223** [comment]
sorry sir for late reply I have internet problem

**Comment by leastprivilege** [comment]
done. thanks!

**Comment by leo9223** [comment]
@leastprivilege Sir I"ll request you to please review and run this App once :)

**Comment by leastprivilege** [comment]
Hi. 

i know nothing about Android - wouldn't be of any help ;)

**Pull request closed without merging**
