### PR TITLE
Fixing relative build reference in docker-compose for IdentityServer.

### PR DESCRIPTION
**Pull request by haukurk**

### CODE REVIEW

**Comment by leastprivilege** [comment]
@tugberkugurlu please review

**Comment by tugberkugurlu** [comment]
This seems to be for the nodejs sample but I can see that it makes sense, :shipit:

**Comment by leastprivilege** [comment]
@AlexZeitler

**Comment by AlexZeitler** [comment]
Makes sense.

**Comment by leastprivilege** [comment]
thanks!

**Pull request merged**
