### PR TITLE
Upgrade to .NET Core 2

### PR DESCRIPTION
**Pull request by ZaChickster**
Based on the API changes between Core 1.1 and 2.0 some changes had to be made.  Also use RC version of the IdentityServer4 package.

### CODE REVIEW

**Comment by leastprivilege** [comment]
Thanks! Don't worry - we will update that once IdentityServer and the docs are ready.

**Comment by ZaChickster** [comment]
That's cool.  No worries.  We're evaluating IdentityServer4 and was upgrading the sample.  Figured if I could save someone else 10 minutes or so might as well.  Still working on API acccess ... 

https://github.com/IdentityServer/IdentityServer4/issues/1466

**Comment by tstojecki** [comment]
Looks like the updates are in version 2 rc1 of IdentityServer4.AccessTokenValidation https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/commit/5ba378c09a8073d339c19ce40152a8fee7091a8f

So if you update the package you can use the IdentityServer extension methods to configure the api

`using IdentityServer4.AccessTokenValidation;`

In ConfigureServices:
`services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
    .AddIdentityServerAuthentication(o =>
                {
                    o.Authority = authority;
                    o.ApiName = apiName;
                    o.RequireHttpsMetadata = false;
                });`

In Configure:
`app.UseAuthentication();`

**Comment by brockallen** [comment]
Closing since we've done the upgrade. Thanks.

**Pull request closed without merging**
