### PR TITLE
Refactored Docker example for better usability

### PR DESCRIPTION
**Pull request by programatt**
I attempted to refactor the docker example to make it a little easier to work with from the development perspective. It appeared that the original setup was more for just a "run with docker" scenario instead of a "develop with docker" scenario if that makes sense. By mounting the source directories into the containers, any changes except a NuGet Package addition/subtraction won't require a container rebuild. And even then you could `docker exec` into the container and run dotnet restore without rebuilding. I also felt like by putting the dockerfiles into the dir for each sub-project in the solution it mapped more closely to a real-world scenario where you are working with multiple separate repositories that can be built independently. This would also allow someone using this as a base to eventually build and push separate images and run 1 or more of the services as a published image instead of building the local source. Let me know if you have interest in these changes I'm open to suggestions and just trying to help make the project better! 

- Moved Dockerfiles and modified docker-compose.yml to isolate each projects dependencies to build images separately.
- Mounted each project source directory into container to enable modify and rebuild.
- Modified each dockerfile to run dotnet watch run to enable modify and rebuild.
- Added Makefile so `make all` command will build and run all containers and show all log output

### CODE REVIEW

**Comment by ThorstenHans** [comment]
@programatt why aren't you batching actions in dockerfiles to create less layers?

**Comment by programatt** [comment]
@ThorstenHans well getting the nuget and csproj in before doing the restore means those layers will be cached as long as the files don't change. I suppose I could have batched them together, but just did it as a first pass. Looks like they don't want the contribution anyways because it seems to have been passed over without comment :(

**Comment by brockallen** [comment]
Who owns this sample? @leastprivilege @tugberkugurlu?

**Comment by brockallen** [comment]
Last call for someone to speak up for this sample, otherwise I'm closing this PR! @tugberkugurlu

**Comment by leastprivilege** [comment]
@tugberkugurlu @programatt We decided to remove all samples that are not written by ourselves. Please rather add a link to your own repo to our docs:

https://identityserver4.readthedocs.io/en/release/quickstarts/community.html

**Pull request closed without merging**
