### PR TITLE
Nodejs api e2e sample

### PR DESCRIPTION
**Pull request by AlexZeitler**
As introduced in #125

### CODE REVIEW

**Comment by leastprivilege** [comment]
thanks! 

could you update to vs2017 + PR against dev?

**Comment by AlexZeitler** [comment]
Ok, will try but need to install 2017 first...

**Comment by leastprivilege** [comment]
I heard it only takes 2 seconds to install ;)

**Comment by AlexZeitler** [comment]
Especially on macOS or Ubuntu 😄

**Comment by AlexZeitler** [comment]
When starting the migration... 🙄 

image

Stay tuned...

**Comment by AlexZeitler** [comment]
Migration done, changed PR to target `dev` branch`.

**Comment by leastprivilege** [comment]
done done?

**Comment by AlexZeitler** [comment]
yes.

**Comment by brockallen** [comment]
I finally took a look -- thanks!

**Comment by AlexZeitler** [comment]
Thanks for merging!

**Pull request merged**
