### PR TITLE
Move docker samples to .NET Core Tools 1.0.0

### LINKED ISSUE #136: Update Docker Sample to csproj
@tugberkugurlu

### PR DESCRIPTION
**Pull request by tugberkugurlu**
Fixes #136.

 - [x] Move from `project.json` to `.csproj`.
 - [x] Update docker files to target SDK ~~v1.0.0~~ [v1.0.1](https://github.com/dotnet/dotnet-docker/blob/master/1.1/debian/sdk/Dockerfile#L20)
 - [x] Add `.dockerignore` file
 - [x] Give it a whirl and update the image on the README.

### CODE REVIEW

**Comment by tugberkugurlu** [comment]
Moved the dockerfiles too but I am getting the below error during image build:

```
Step 10/14 : RUN dotnet restore
 ---> Running in 3a0437643075
  Restoring packages for /app/IdentityServerWithAspNetIdentity.csproj...
  Restoring packages for /app/IdentityServerWithAspNetIdentity.csproj...
  Installing Microsoft.NETCore.Jit 1.0.4.
  Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.4.
  Installing Microsoft.NETCore.DotNetHostPolicy 1.0.1.
  Installing Microsoft.NETCore.App 1.1.0.
  Installing NUglify 1.5.5.
  Installing BundlerMinifier.Core 2.4.337.
  Restore completed in 3.11 sec for /app/IdentityServerWithAspNetIdentity.csproj.
  Restoring packages for /app/IdentityServerWithAspNetIdentity.csproj...
  Installing Microsoft.NETCore.Jit 1.0.2.
  Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.2.
  Installing Microsoft.Extensions.SecretManager.Tools 1.0.0.
  Installing Microsoft.NETCore.App 1.0.0.
  Restore completed in 415.86 ms for /app/IdentityServerWithAspNetIdentity.csproj.
  Installing Microsoft.IdentityModel.Logging 1.1.0.
  Installing Microsoft.IdentityModel.Tokens 5.1.0.
  Installing Microsoft.Extensions.Options 1.1.0.
  Installing Microsoft.AspNetCore.Cryptography.Internal 1.1.0.
  Installing System.IdentityModel.Tokens.Jwt 5.1.0.
  Installing Microsoft.AspNetCore.Cors 1.1.0.
  Installing Microsoft.Extensions.Caching.Memory 1.1.0.
  Installing IdentityModel 2.1.1.
  Installing Microsoft.Extensions.Caching.Abstractions 1.1.0.
  Installing Microsoft.AspNetCore.Cryptography.KeyDerivation 1.1.0.
  Installing IdentityServer4 1.0.0.
  Installing Microsoft.AspNetCore.Identity 1.1.0.
  Installing Microsoft.AspNetCore.Authentication.OAuth 1.1.1.
  Installing IdentityServer4.AspNetIdentity 1.0.0.
  Installing Microsoft.AspNetCore.Authentication.Google 1.1.1.
  Installing Microsoft.EntityFrameworkCore.InMemory 1.1.1.
  Generating MSBuild file /app/obj/IdentityServerWithAspNetIdentity.csproj.nuget.g.props.
  Generating MSBuild file /app/obj/IdentityServerWithAspNetIdentity.csproj.nuget.g.targets.
  Writing lock file to disk. Path: /app/obj/project.assets.json
  Restore completed in 4.71 sec for /app/IdentityServerWithAspNetIdentity.csproj.

  NuGet Config files used:
      /app/NuGet.Config
      /root/.nuget/NuGet/NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json

  Installed:
      29 package(s) to /app/IdentityServerWithAspNetIdentity.csproj
 ---> 4374fcbc6da7
Removing intermediate container 3a0437643075
Step 11/14 : ADD ./src/IdentityServerWithAspNetIdentity/ /app/
 ---> 284fc5ac5924
Removing intermediate container 05f179533907
Step 12/14 : RUN dotnet publish -c Debug -o out
 ---> Running in d08415194680
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(154,5): error : Assets file '/app/D:/Dev/IdentityServer4.Samples/Docker/src/IdentityServerWithAspNetIdentity/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/app/IdentityServerWithAspNetIdentity.csproj]
/tmp/.NETCoreApp,Version=v1.1.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [/app/IdentityServerWithAspNetIdentity.csproj]
```

Not entirely sure why. @MichaelSimons thoughts?

**Comment by MichaelSimons** [comment]
@tugberkugurlu, hmm, not knowing how you migrated the project, I quickly ran `dotnet migrate` myself.  Looks like you did the same as I came up with the same results - https://github.com/MichaelSimons/IdentityServer4.Samples/tree/msbuild-migration.  Everything built without error when I ran `docker-compose build`.  Do you have any old artifacts laying around that could be causing issues?  Have you run something like `git clean -fdx` to see if this helps?

**Comment by tugberkugurlu** [comment]
> Do you have any old artifacts laying around that could be causing issues? Have you run something like git clean -fdx to see if this helps?

Yes, that turned out to be the case 😞 thanks for checking it out 👍 I am looking into getting a dockerignore file now.

> Looks like you did the same as I came up with the same results - 

yep, I ran `dotnet migrate` on `global.json` file.

**Comment by leastprivilege** [comment]
finished?

**Comment by tugberkugurlu** [comment]
> finished?

nope, hold your horses a little bit more.

**Comment by tugberkugurlu** [comment]
@leastprivilege Works as expected AFA I can see. Good to merge now, :shipit: 

image

image

**Comment by leastprivilege** [comment]
thanks!!

**Pull request merged**
