### PR TITLE
Update _LoginPartial.cshtml

### PR DESCRIPTION
**Pull request by vmh32**
After logout the user is still showing as signed in.

### CODE REVIEW

**Comment by tstojecki** [comment]
@brockallen, this happened for us too and the ViewData 'fix' did the trick.

Also, it looks like the samples for aspnet identity and EF diverge from the UI sample quite a bit, which isn't the case for something like the hybrid sample (5_HybridFlowAuthenticationWithApiAccess). The app is structured differently, different logic in controllers and views. Is that on purpose?

**Comment by brockallen** [comment]
Yep, this was just an oversight when migrating to aspnetcore 2. On the other hand, hopefully you realize the quickstart UI is really just sample code that you're expected to fully control for your needs. But yea, I'll merge this when I am back at a desk/computer. Thanks!

**Comment by tstojecki** [comment]
Hi @brockallen , your point about sample code is well taken. I was just noticing the changes in 6_AspNetIdentity seem to be going beyond configuring aspnet identity compared to other projects in Quickstarts folder.

**Comment by brockallen** [comment]
Thanks!

**Pull request merged**
